exp_id: debug
tasks: all
bs: 4
num_workers: 3
epochs: 100
train_iter: 160000
sample_distribution_mode: task_uniform
peract:
  lr: 8e-5 # 
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
rvt:
  place_with_mean: False
  img_aug: 0.0
