name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      # - uses: pre-commit/action@v3.0.1
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
        with:
          # 对所有文件都运行
          extra_args: ['--all-files']
          # 跳过会因中文导致失败的那个 hook
          skip: ['check-commit-msg']